### ISSUE TITLE
Unable to scroll the page down when touching <skeleton-carousel> in mobile device

### ISSUE THREAD

**Issue by andrewspy** [FabricElements/skeleton-carousel#73] opened 2018-06-05 08:45 UTC
In mobile device (especially in landscape mode), carousel usually occupy most of the screen, and it's not possible for user to scroll down the page by touching `<skeleton-carousel>`.

To see the issue, just check out the `<skeleton-carousel>`'s [demo page](https://www.webcomponents.org/element/FabricElements/skeleton-carousel/demo/demo/index.html) with your mobile device, and scrolling down the page by touching the carousel.

**Comment by ernysans** [comment] 2018-06-05 12:37
@stivaliserna Please review this on Polymer 3 first.

**Comment by andrewspy** [comment] 2018-06-06 09:01
Just wanted to add that Mobile Safari does not suffer from the issue. So far I have encountered the issue on Mobile Chrome (Android) and Desktop Chrome (Windows 10 with touch screen)

**Comment by andrewspy** [comment] 2018-06-07 20:57
Will there be a fix for Polymer 2? I presume lots of project in production are still in Polymer 2.

**Comment by ernysans** [comment] 2018-06-08 12:28
@andrewspy The issue is fixed in polymer 3. We are migrating all our components to Polymer 3 and we don't have time the next couple of weeks because of that, we can review this once we complete the migration. We need to move more than 40 repositories.
You can also check the changes we did to solve this issue in master and send a PR to our branch 2.0 so we just check that and close it.

**Comment by andrewspy** [comment] 2018-06-09 12:11
@ernysans Thanks for the info, at least we know that polymer 2.0 fix is in the pipeline.

**Comment by bennypowers** [comment] 2018-06-17 21:38
Had this same issue on Chrome. This was a very welcome fix. Thank you!

**Comment by ernysans** [comment] 2018-06-19 13:44
Bug fixes coming on our next release. We are merging improvements on 2.0 today! 😎

**Closed** 2018-06-19 17:40 UTC
Labels: bug
